--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/CustomAlerts
branches:
- patch-2
projects:
  CustomAlerts:
    path: CustomAlerts/
  CustomAlertsExample:
    path: CustomAlertsExample/
...
